# numpy

```
pip install numpy
```


- https://numpy.org/devdocs/user/quickstart.html
- https://datascienceschool.net/01%20python/03.01%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%B0%EC%97%B4.html
- https://datascienceschool.net/01%20python/03.04%20%EA%B8%B0%EC%88%A0%20%ED%86%B5%EA%B3%84.html

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])   # 1x4 배열, 행렬
a

array([1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

1차원

In [14]:
a = np.array([1.0,2.1,3,4])   # 4x1 배열, 행렬
a.dtype

dtype('float64')

In [15]:
a

array([1. , 2.1, 3. , 4. ])

In [16]:
a1 = np.array([[1.0,2.1,3,4]])   # 4x1 배열, 행렬
a1

array([[1. , 2.1, 3. , 4. ]])

2차원

In [8]:
a2 = np.array([[1.0,2.1,3.0,4.0],
             [0.1, 2.0, 9.0, 10.0]])   # 2x4 배열, 행렬
a2

array([[ 1. ,  2.1,  3. ,  4. ],
       [ 0.1,  2. ,  9. , 10. ]])

속성

In [11]:
a.dtype, a2.dtype

(dtype('float64'), dtype('float64'))

In [17]:
a.shape, a1.shape, a2.shape

((4,), (1, 4), (2, 4))

In [18]:
a.ndim, a1.ndim, a2.ndim

(1, 2, 2)

np.arange()

In [19]:
arr1 = np.arange(30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
arr1.ndim

1

In [21]:
type(arr1)

numpy.ndarray

np.reshape()  : shape 변형

In [26]:
arr1 = np.arange(30).reshape(5,6)     # 5x6
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
arr1.ndim

2

In [24]:
arr1 = arr1.reshape(30,)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
arr1.ndim

1

In [28]:
arr2 = np.ndarray(shape=(5,6), dtype='float64')
arr2

array([[9.26985393e-312, 9.63428009e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307, 1.16097020e-028],
       [6.37112413e-067, 9.71520605e-067, 1.57177609e-076,
        5.01163173e+217, 8.37170074e-144, 1.82627997e+184],
       [1.38058550e-047, 4.71004124e-090, 2.64828814e-032,
        5.01163114e+217, 5.49419094e-143, 3.68777431e+180],
       [5.56111702e+180, 7.49874326e+247, 1.45187131e-057,
        7.79174295e-091, 1.45082388e-047, 1.52516743e-052],
       [1.58692292e-047, 1.47763641e+248, 1.16096346e-028,
        1.28625693e+248, 4.24948967e-086, 2.59297862e-306]])

In [29]:
arr2.shape, arr2.ndim

((5, 6), 2)

#### 영행렬, 일행렬

In [30]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

np.random.randn()

In [32]:
arr = np.random.randn(2,3)
arr

array([[ 1.36170544, -0.21349764,  1.08526124],
       [ 0.25120121, -0.86467758, -0.14223523]])

np.array()

In [33]:
arr1 = np.array([[1,2,3],
                [4,5,6]], dtype='float64')
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr1 = np.array([[1,2,3],
                [4,5,6]], dtype=np.uint64)
arr1.dtype, arr1.shape

(dtype('uint64'), (2, 3))

In [37]:
arr1 = arr1.astype(np.float16)
arr1.dtype

dtype('float16')

#### 사칙연산

In [38]:
arr1 = np.array([[1,2,3],
                [4,5,6]], dtype=np.float64)
arr1.dtype, arr1.shape

(dtype('float64'), (2, 3))

In [40]:
arr2 = np.array([[7,8,9],
                [10,11,12]], dtype=np.float64)
arr2.dtype, arr2.shape

(dtype('float64'), (2, 3))

In [41]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr2 - arr1

array([[6., 6., 6.],
       [6., 6., 6.]])

In [43]:
arr2 / arr1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [44]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

### indexing

In [55]:
arr1 = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]], dtype='float64')
arr1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [46]:
arr1[0][3]

4.0

In [47]:
arr1[0][2:4]

array([3., 4.])

In [48]:
arr1[[1,2]]

array([[ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [49]:
arr1[1]

array([ 6.,  7.,  8.,  9., 10.])

차원을 가진 배열로 접근해 주세요!!!

In [51]:
arr1[[1]]

array([[ 6.,  7.,  8.,  9., 10.]])

In [52]:
arr1[[1]] = np.array([0,0,0,0,0])
arr1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  0.,  0.,  0.,  0.],
       [11., 12., 13., 14., 15.]])

In [53]:
arr1[[1]] = 100
arr1

array([[  1.,   2.,   3.,   4.,   5.],
       [100., 100., 100., 100., 100.],
       [ 11.,  12.,  13.,  14.,  15.]])

In [54]:
arr1[:] = 0
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Slicing

In [57]:
arr1[[0], 2:4]

array([[3., 4.]])

In [58]:
arr1[[0], :]

array([[1., 2., 3., 4., 5.]])

In [59]:
arr1[[0], [1,2]]

array([2., 3.])

In [60]:
arr1[:, [1,2]]

array([[ 2.,  3.],
       [ 7.,  8.],
       [12., 13.]])

#### Fancy indexing

- 1) 논리 조건
- 2) 필터
- 3) ndarray 등에 일치하는 인덱스 요소

In [62]:
# index
arr = np.array([1,2,3,4,5,6])
idx = np.array([False, True, True, False, False, True])

In [67]:
arr[[3,4]]

array([4, 5])

In [63]:
arr[idx]

array([2, 3, 6])

In [64]:
arr % 2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [65]:
arr % 2 == 0

array([False,  True, False,  True, False,  True])

In [66]:
arr[ arr % 2 == 0 ]

array([2, 4, 6])

#### Inf, NaN
 - 무한대
 - Not a Number

In [68]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [69]:
np.inf

inf

In [70]:
np.log(0)

C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [72]:
np.array([10]) / 

array([0.])

## 실습:



####  라텍스: markdown

 - https://ko.wikipedia.org/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:TeX_%EB%AC%B8%EB%B2%95



표: 칼로리

상품 | 칼로리
------ | ----------
사과 | 145kcal/1개
우유 | 134kcal/1병
바나나| 72kcal/1개

표: 섭취량

이름 | 사과 | 우유 | 바나나
------ | ----- | ----- | -----
철수 | 1 | 2 | 3
영희 | 2 | 1 | 1

표: 가격

상품 | 편의점 | 슈퍼마켓 | 백화점
------ | ----- | ----- | -----
사과 | 1,500원 | 1,600원 | 2,500원
우유 | 2,400원 | 2,200원 | 6,800원
바나나 | 1,300원 | 1,100원 | 2,300원

이 조사 테이블을 수학적으로 표현하면 의미있는 숫자만으로 행렬로 표현할 수 있다.

$$
\begin{pmatrix} 145 \\ 134 \\ 72 
\end{pmatrix}
\\
\begin{pmatrix} 
1500 & 1600 & 2500 \\
2400 & 2200 & 6800 \\
1300 & 1100 & 2300 \end{pmatrix}
$$

$$
\sqrt[3]{x^3+y^3 \over 2}
$$

$$
\begin{bmatrix}
0 & \cdots & 0 \\
\vdots & \ddots & \vdots \\
0 & \cdots & 0
\end{bmatrix}
$$

#### 기술통계 실습

 - https://datascienceschool.net/01%20python/03.04%20%EA%B8%B0%EC%88%A0%20%ED%86%B5%EA%B3%84.html
 
라텍스 문법도 작성해서 정리하고, ndarray 로 기술통계 수치를 확인해 보자.